server.port=${PORT:8080}

# Spring Data MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://nividharan452007_db_user:NexusPass2026@cluster0.rpu0pnn.mongodb.net/nexuscommerce?retryWrites=true&w=majority

# JWT Token Security Config
jwt.secret=NexusCommerceSuperSecretKey2026ForB2BCatalogPipelineSecurity
jwt.expiration=86400000

# Logging Levels
logging.level.org.springframework.web=INFO
logging.level.com.nexuscommerce=DEBUG
